version: '3'

services:
  dashboard:
    restart: unless-stopped
    container_name: dashboard
    build:
      context: .
      dockerfile: ./dashboard/Dockerfile
    environment:
      POSTGRES_DB: "ghost_storage"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Jad108fsdlknzc"
    networks:
      node_net:
        ipv4_address: 172.28.1.9
    ports:
      - 8085:8085
    volumes:
      - ./dashboard:/app

  ghost_proj:
    restart: unless-stopped
    container_name: ghost_proj
    build:
      context: .
      dockerfile: ./ghost_stor/Dockerfile
    networks:
      node_net:
        ipv4_address: 172.28.1.10
    depends_on:
      - postgres
    ports:
      - 8080:8080
    volumes:
      - ./ghost_stor:/ghost_stor
      - ./ghost_stor/src/files:/files

  postgres:
    image: postgres:14.2
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: "ghost_storage"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Jad108fsdlknzc"
    networks:
      node_net:
        ipv4_address: 172.28.1.3
    volumes:
      - ./pg_storage:/var/lib/postgresql/data
    ports:
      - 5436:5432


networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16