version: '3'

services:
  dashboard:
    restart: unless-stopped
    container_name: dashboard
    image: k1n5/ghost_dashboard
    build:
      context: .
      dockerfile: ./dashboard/Dockerfile
    environment:
      POSTGRES_DB: "ghost_storage"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Jad108fsdlknzc"
      HOST: ${HOST}
      PORT: ${PORT}
      DASHBOARD_PORT: ${DASHBOARD_PORT}
    networks:
      node_net:
        ipv4_address: 172.28.1.9
    depends_on:
      - postgres
    ports:
      - ${DASHBOARD_PORT}:${DASHBOARD_PORT}
    volumes:
      - ./dashboard:/dashboard

  ghost_proj:
    restart: unless-stopped
    container_name: ghost_proj
    image: k1n5/ghost_rep
    build:
      context: .
      dockerfile: ./ghost_stor/Dockerfile
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      DASHBOARD_PORT: ${DASHBOARD_PORT}
    networks:
      node_net:
        ipv4_address: 172.28.1.10
    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./ghost_stor:/ghost_stor
      - ./ghost_stor/src/files:/files

  postgres:
    image: postgres:14.2
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: "ghost_storage"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Jad108fsdlknzc"
    networks:
      node_net:
        ipv4_address: 172.28.1.3
    volumes:
      - ./pg_storage:/var/lib/postgresql/data
    ports:
      - 5436:5432


networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
